<a href="https://colab.research.google.com/github/Ansarss/Ai_learning_experiments/blob/main/daily_mean_temperature_with_a_Gaussian_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sumanthvrao/daily-climate-time-series-data")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'daily-climate-time-series-data' dataset.
Path to dataset files: /kaggle/input/daily-climate-time-series-data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
import os

print("Dataset folder:", path)
print(os.listdir(path))

Dataset folder: /kaggle/input/daily-climate-time-series-data
['DailyDelhiClimateTrain.csv', 'DailyDelhiClimateTest.csv']

In [9]:
import pandas as pd

train_path = os.path.join(path, "DailyDelhiClimateTrain.csv")
test_path = os.path.join(path, "DailyDelhiClimateTest.csv")

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

print("Training shape:", train_df.shape)
print("Testing shape:", test_df.shape)

train_df.head()

Training shape: (1462, 5)
Testing shape: (114, 5)

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000

In [10]:
print(train_df.columns)

train_df.info()

Index(['date', 'meantemp', 'humidity', 'wind_speed', 'meanpressure'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   object
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: float64(4), object(1)
memory usage: 57.2+ KB

In [11]:
train_df.isnull().sum()

date            0
meantemp        0
humidity        0
wind_speed      0
meanpressure    0
dtype: int64